name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x

      # Create a temp .npmrc to authenticate with GPR.
      - name: Create CI .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @showbie:registry=https://npm.pkg.github.com/
            //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
          EOF
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/bahmutov/npm-install
      # Custom install command to prevent husky from installing.
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --ignore-scripts --no-audit --legacy-peer-deps

      - name: Bootstrap monorepo
        run: npm run bootstrap

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
